//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receipe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMS_LIVEEntities : DbContext
    {
        public HMS_LIVEEntities()
            : base("name=HMS_LIVEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rcp_ingredients_costsheet_child_t> rcp_ingredients_costsheet_child_t { get; set; }
        public virtual DbSet<rcp_ingredients_costsheet_parent_t> rcp_ingredients_costsheet_parent_t { get; set; }
        public virtual DbSet<rcp_ingredients_list_t> rcp_ingredients_list_t { get; set; }
        public virtual DbSet<rcp_production_t> rcp_production_t { get; set; }
        public virtual DbSet<rcp_recipe_child_t> rcp_recipe_child_t { get; set; }
        public virtual DbSet<rcp_recipe_parent_t> rcp_recipe_parent_t { get; set; }
        public virtual DbSet<pos_measurement_t> pos_measurement_t { get; set; }
    }
}
