//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receipe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_measurement_t
    {
        public string code { get; set; }
        public string description { get; set; }
        public bool is_fraction { get; set; }
        public string creator { get; set; }
        public System.DateTime creationdate { get; set; }
        public string modifier { get; set; }
        public System.DateTime modificationdate { get; set; }
        public Nullable<short> is_receipe_unit { get; set; }
    }
}
