//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receipe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rcp_ingredients_costsheet_parent_t
    {
        public int id { get; set; }
        public System.DateTime effective_from_date { get; set; }
        public System.DateTime effective_to_date { get; set; }
    }
}
